export const AppRoutes = {
  '404': '/404',
  wallet: '/wallet',
  trademark: '/trademark',
  token: '/token',
  terms: '/terms',
  privacy: '/privacy',
  press: '/press',
  pass: '/pass',
  index: '/',
  imprint: '/imprint',
  governance: '/governance',
  gasStation: '/gas-station',
  ecosystem: '/ecosystem',
  disclaimer: '/disclaimer',
  dataroom: '/dataroom',
  core: '/core',
  cookie: '/cookie',
  cla: '/cla',
  careers: '/careers',
  blog: {
    index: '/blog',
    slug: '/blog/[slug]',
  },
  campaigns: {
    slug: '/campaigns/[slug]',
  },
}
