name: Unit tests
on:
  pull_request:

  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v5

      - uses: ./.github/workflows/yarn

      - name: Run tests
        run: 'yarn test:ci'

      - name: Comment in failing tests
        uses: mattallty/jest-github-action@v1.0.3
        if: failure()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: 'echo unit tests already executed'
          coverage-comment: false
